/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssignmentPanel: typeof import('./components/Editor/TextureSelector/AssignmentPanel.vue')['default']
    Brand: typeof import('./components/Header/Brand.vue')['default']
    CodeMirror: typeof import('./components/Editor/CodeMirror.vue')['default']
    CollapsiblePanel: typeof import('./components/panel/CollapsiblePanel.vue')['default']
    ControlPanel: typeof import('./components/Preview/ControlPanel.vue')['default']
    ExportShader: typeof import('./components/Header/ExportShader.vue')['default']
    FullscreenButton: typeof import('./components/Preview/FullscreenButton.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    Index: typeof import('./components/Editor/TextureSelector/Index.vue')['default']
    InfoPanel: typeof import('./components/Preview/InfoPanel.vue')['default']
    Item: typeof import('./components/Tabs/Item.vue')['default']
    PanelGroup: typeof import('./components/panel/PanelGroup.vue')['default']
    PassEditor: typeof import('./components/Editor/PassEditor.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Preview: typeof import('./components/Preview/Preview.vue')['default']
    Share: typeof import('./components/Header/Share.vue')['default']
    Slot: typeof import('./components/Editor/TextureSelector/Slot.vue')['default']
    TabBar: typeof import('./components/Tabs/TabBar.vue')['default']
    ThemeToggle: typeof import('./components/Header/ThemeToggle.vue')['default']
    VersionSelector: typeof import('./components/Header/VersionSelector.vue')['default']
  }
}
