/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Brand: typeof import('./components/Header/Brand.vue')['default']
    Editor: typeof import('./components/Editor/Editor.vue')['default']
    Header: typeof import('./components/Header/Header.vue')['default']
    Playground: typeof import('./components/Playground.vue')['default']
    Preview: typeof import('./components/Preview/Preview.vue')['default']
    Share: typeof import('./components/Header/Share.vue')['default']
    ThemeToggle: typeof import('./components/Header/ThemeToggle.vue')['default']
    VersionSelector: typeof import('./components/Header/VersionSelector.vue')['default']
  }
}
